import { expect, test } from '@playwright/test';

test('创建共享目录并动态添加班型', async ({ page }) => {
  const familyName = `共享目录界面验收 ${Date.now()}`;
  await page.goto('/login');
  await page.getByLabel('手机号').fill('13800000001');
  await page.getByLabel('密码').fill('123456');
  await page.getByRole('button', { name: '进入工作台' }).click();
  await expect(page.getByRole('heading', { name: '今日待办' })).toBeVisible();
  await page.goto('/content');
  await expect(page.getByRole('heading', { name: '共享目录课程系列' })).toBeVisible();
  await page.getByRole('button', { name: '新增课程系列' }).click();
  const setup = page.getByRole('dialog', { name: '新增课程系列 · 选择班型' });
  await setup.getByRole('combobox', { name: '课程系列范围' }).fill('五年级');
  await page.locator('.ant-select-item-option').filter({ hasText: /五年级.*English.*S1.*Q1/ }).first().click();
  await setup.locator('.ant-checkbox-wrapper').filter({ hasText: /^S\+ ·/ }).click();
  await setup.locator('.ant-checkbox-wrapper').filter({ hasText: /^H ·/ }).click();
  await setup.getByRole('button', { name: '下一步：编辑共享目录' }).click();
  const drawer = page.getByRole('dialog', { name: '新增课程系列 · 编辑共享目录' });
  await drawer.getByLabel('课程名称').fill(familyName);
  await drawer.getByRole('button', { name: '新增 Unit' }).click();
  await drawer.getByLabel('Unit名称（必填）').fill('Unit 1 · Shared');
  await drawer.getByRole('button', { name: '新增 Chapter' }).click();
  await drawer.getByLabel('Chapter名称（必填）').fill('Chapter 1 · Reading');
  await drawer.getByRole('button', { name: '新增 Lesson' }).click();
  await drawer.getByLabel('Lesson名称（必填）').fill('Lesson 1 · Introduction');
  await page.locator('.ant-drawer-footer button.ant-btn-primary').click();
  await expect(drawer).toBeHidden();
  const row = page.locator('.ant-table-tbody tr').filter({ hasText: familyName });
  await expect(row).toContainText('S+');
  await expect(row).toContainText('H');
  await expect(row).toContainText('1 Unit');
  await expect(row).toContainText('1 Lesson');
  await row.getByRole('button', { name: '添加班型' }).click();
  const add = page.getByRole('dialog', { name: `为“${familyName}”添加班型` });
  await add.getByRole('combobox', { name: '选择新增班型' }).click();
  await page.locator('.ant-select-dropdown:not(.ant-select-dropdown-hidden) .ant-select-item-option').filter({ hasText: /^S ·/ }).first().click();
  await add.getByRole('button', { name: '添加班型' }).click();
  await expect(add).toBeHidden();
  await expect(row).toContainText('S');
  await expect(row).toContainText('S+');
  await expect(row).toContainText('H');
  await page.getByPlaceholder('搜索课程').fill(familyName);
  await expect(page.locator('.ant-table-tbody tr').filter({ hasText: familyName })).toHaveCount(1);
  await expect(page.locator('.ant-message')).toBeHidden();
  await page.screenshot({ path: '../docs/课程系列共享目录_实施预览.png', fullPage: true });
  await row.getByRole('button', { name: '管理目录' }).click();
  const edit = page.getByRole('dialog', { name: '编辑课程系列共享目录' });
  await expect(edit.getByLabel('Lesson名称（必填）')).toHaveValue('Lesson 1 · Introduction');
});
