import { test, expect } from '@playwright/test';
test('教师明确标记异常，重开可见并恢复批改；真实本地接口',async({page,request})=>{
 test.skip(!process.env.STARLINE_REAL_REVIEW_API,'launched by isolated Go integration');
 const token=process.env.STARLINE_REAL_REVIEW_TOKEN!;const user=JSON.parse(process.env.STARLINE_REAL_REVIEW_USER!);
 const api=process.env.STARLINE_REAL_REVIEW_API!;const headers={Authorization:`Bearer ${token}`};
 await page.addInitScript(({token,user})=>{localStorage.setItem('starline_admin_token',token);localStorage.setItem('starline_admin_user',JSON.stringify(user));},{token,user});
 await page.goto('/content?tab=review');
 await page.getByRole('button',{name:'标记异常',exact:true}).click();
 const modal=page.getByRole('dialog',{name:'标记批改异常',exact:true});
 await modal.getByRole('button',{name:'保存异常',exact:true}).click();
 await expect(modal.getByText('请填写实际班级名称',{exact:true})).toBeVisible();
 await modal.getByRole('textbox',{name:'实际班级',exact:true}).fill('隔离测试班');
 await modal.getByRole('combobox',{name:'异常原因',exact:true}).click();
 await page.locator('.ant-select-item-option-content').getByText('作业缺页',{exact:true}).click();
 await modal.getByRole('button',{name:'保存异常',exact:true}).click();
 await expect(modal).not.toBeVisible();
 await expect(page.getByText('隔离测试班 · 作业缺页',{exact:true})).toBeVisible();
 await page.reload();await expect(page.getByText('隔离测试班 · 作业缺页',{exact:true})).toBeVisible();
 const response=await request.get(`${api}/api/reviews/pending`,{headers});expect(response.ok()).toBeTruthy();
 const review=(await response.json()).data.find((r:{id:string})=>r.id==='rev-001');
 expect(review.status).toBe('批改异常');expect(review.exceptionEventId).toBeTruthy();expect(review.systemScore).toBe(86);
 await page.setViewportSize({width:390,height:844});
 await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
 await page.screenshot({path:'/tmp/starline-review-exception-narrow.png',fullPage:true});
 await page.getByRole('button',{name:'标记异常',exact:true}).click();
 await modal.getByRole('button',{name:'保存异常',exact:true}).click();await expect(modal).not.toBeVisible();
 const again=await request.get(`${api}/api/reviews/pending`,{headers});
 expect((await again.json()).data.find((r:{id:string})=>r.id==='rev-001').exceptionEventId).toBe(review.exceptionEventId);
 await page.setViewportSize({width:1280,height:900});
 await page.getByRole('button',{name:'填写反馈',exact:true}).click();
 const feedback=page.getByRole('dialog',{name:'填写批改反馈'});
 await feedback.locator('.ant-select-selector').click();await page.locator('.ant-select-item-option-content').getByText('待复核',{exact:true}).click();
 await feedback.getByRole('button',{name:'发送反馈',exact:true}).click();await expect(feedback).not.toBeVisible();
 await expect(page.getByText('隔离测试班 · 作业缺页',{exact:true})).toHaveCount(0);
 const cleared=await request.get(`${api}/api/reviews/pending`,{headers});
 const latest=(await cleared.json()).data.find((r:{id:string})=>r.id==='rev-001');expect(latest.status).toBe('待复核');expect(latest.exceptionReason).toBeFalsy();expect(latest.exceptionEventId).toBeFalsy();
});
