import { test, expect } from '@playwright/test';

test('actual teacher form keeps grouped teaching and extra reading separate after saving', async ({ page, request }) => {
 test.skip(!process.env.STARLINE_REAL_API, 'launched by isolated Go browser integration');
 const token=process.env.STARLINE_REAL_TOKEN!;
 const user=JSON.parse(process.env.STARLINE_REAL_USER!);
 const headers={Authorization:`Bearer ${token}`};
 await page.addInitScript(({token,user})=>{localStorage.setItem('starline_admin_token',token);localStorage.setItem('starline_admin_user',JSON.stringify(user));localStorage.setItem('starline:list-view:teachers','table');},{token,user});
 await page.goto('/teachers');
 await page.getByRole('button',{name:/新增教师/}).click();
 const drawer=page.getByRole('dialog',{name:'新增教师',exact:true});
 await drawer.getByPlaceholder('例如：英语老师',{exact:true}).fill('范围联验老师');
 await drawer.getByPlaceholder('用于首次登录和身份确认',{exact:true}).fill('18000011113');
 const select=async(label:string,value:string,target=drawer)=>{
  const combo=target.getByRole('combobox',{name:label,exact:true}).last();
  await combo.scrollIntoViewIfNeeded();
  await target.locator('.ant-select').filter({has:page.getByRole('combobox',{name:label,exact:true})}).last().locator('.ant-select-selector').click();
  const listID=await combo.getAttribute('aria-controls');
  await page.locator('.ant-select-dropdown').filter({has:page.locator(`[id=${JSON.stringify(listID)}]`)}).getByText(value,{exact:true}).click();
 };
 for(const subject of ['English','Mathematics']) {
  await drawer.getByRole('button',{name:'添加授课范围',exact:true}).click();
  await select('授课年级','五年级');await select('授课学科',subject);
 }
 await drawer.getByText('额外资料查阅范围',{exact:true}).click();
 await drawer.getByRole('button',{name:'添加查阅范围',exact:true}).click();
 await select('查阅年级','六年级');await select('查阅学科','English');
 await drawer.getByLabel('允许下载原文件',{exact:true}).scrollIntoViewIfNeeded();
 await drawer.getByLabel('允许下载原文件',{exact:true}).click();
 await drawer.getByRole('button',{name:/保\s*存/}).click();
 await expect(drawer).not.toBeVisible();
 await page.getByRole('dialog',{name:'临时密码',exact:true}).getByRole('button',{name:'我已记录',exact:true}).click();
 const listResponse=await request.get(`${process.env.STARLINE_REAL_API}/api/teachers`,{headers});
 expect(listResponse.ok()).toBeTruthy();
 const teacher=(await listResponse.json()).data.find((item:{phone:string})=>item.phone==='18000011113');
 expect(teacher).toBeTruthy();
 const spacesResponse=await request.get(`${process.env.STARLINE_REAL_API}/api/learning-spaces`,{headers});
 const spaces=(await spacesResponse.json()).data;
 const expected=spaces.filter((space:{grade:string;subject:string;status:string})=>space.grade==='五年级'&&['英文','English','英语','数学','Math','Mathematics'].includes(space.subject)&&space.status==='启用').map((space:{id:string})=>space.id).sort();
 expect(expected.length).toBeGreaterThan(2);
 expect([...teacher.learningSpaceIds].sort()).toEqual(expected);
 expect([...teacher.teacherLibrary.spaceIds].sort()).toEqual(expected);
 expect(teacher.teacherLibrary.scopes).toEqual([{grade:'六年级',subject:'英文'}]);
 expect(teacher.teacherLibrary.canDownload).toBe(false);
 expect(teacher.teacherLibrary.canManageCourses).toBe(false);
 expect(teacher.canUploadHandout).toBe(false);expect(teacher.canUploadQuestion).toBe(false);expect(teacher.canReview).toBe(false);
 await page.reload();
 const row=page.getByRole('row').filter({hasText:'18000011113'});
 await expect(row.locator('td').first().locator('.ant-tag')).toHaveCount(3);
 await expect(page.getByRole('row').filter({hasText:'13800000004'})).toContainText('特殊授课范围');
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
 await page.screenshot({path:'/tmp/starline-teacher-scope-list-real.png',fullPage:false});
 await row.getByRole('button',{name:'编辑',exact:true}).click();
 const edit=page.getByRole('dialog',{name:'编辑教师',exact:true});
 await expect(edit.getByRole('combobox',{name:'授课年级',exact:true})).toHaveCount(2);
 await expect(edit.getByLabel('资料查阅跟随授课范围',{exact:true})).toBeChecked();
 await expect(edit.getByLabel('允许下载原文件',{exact:true})).not.toBeChecked();
 await expect(edit.getByLabel('允许维护课程',{exact:true})).not.toBeChecked();
 await edit.getByText('额外资料查阅范围',{exact:true}).click();
 await expect(edit.locator('.ant-select').filter({has:page.getByRole('combobox',{name:'查阅年级',exact:true})})).toContainText('六年级');
 await page.screenshot({path:'/tmp/starline-teacher-scope-real.png',fullPage:false});
 await edit.getByRole('button',{name:/保\s*存/}).click();
 await expect(edit).not.toBeVisible();
 const again=await request.get(`${process.env.STARLINE_REAL_API}/api/teachers`,{headers});
 const after=(await again.json()).data.find((item:{id:string})=>item.id===teacher.id);
 expect([...after.learningSpaceIds].sort()).toEqual(expected);
 expect(after.teacherLibrary).toEqual(teacher.teacherLibrary);
 const readOnlyResponse=await request.post(`${process.env.STARLINE_REAL_API}/api/teachers`,{headers,data:{name:'仅查阅联验老师',phone:'18000011115',learningSpaceIds:[],teacherLibrary:{spaceIds:[],scopes:[{grade:'六年级',subject:'英文'}],canDownload:false,canManageCourses:false,canViewDrafts:false},canUploadHandout:false,canUploadQuestion:false,canReview:false}});
 expect(readOnlyResponse.ok()).toBeTruthy();
 await page.reload();
 const readOnlyRow=page.getByRole('row').filter({hasText:'18000011115'});
 await expect(readOnlyRow).toContainText('未分配');
 await expect(readOnlyRow.locator('td').first()).toContainText('六年级 · English');
 await expect(readOnlyRow.locator('td').first()).not.toContainText('五年级');
 // Exercise the actual inline edit while retaining a filled scheduling draft.
 const courseResponse=await request.get(`${process.env.STARLINE_REAL_API}/api/courses`,{headers});
 const originalCourse=(await courseResponse.json()).data.find((item:{id:string})=>item.id==='course-g05-english-s1-q1');
 expect(originalCourse).toBeTruthy();
 const extraCourseResponse=await request.post(`${process.env.STARLINE_REAL_API}/api/courses`,{headers,data:{name:'六年级范围联验课程',learningSpaceId:'space-g06-english-s1-q1',status:'启用',curriculum:[{id:'scope-real-u1',type:'unit',name:'第一课',sortOrder:1}]}});
 expect(extraCourseResponse.ok()).toBeTruthy();
 await page.goto('/scheduling');
 await page.getByRole('button',{name:'新建课程',exact:true}).click();
 const draft=page.getByRole('dialog',{name:'新建课程',exact:true});
 const pick=async(id:string,label:string)=>{
  const combo=draft.locator(`#${id}`);await combo.scrollIntoViewIfNeeded();
  await draft.locator('.ant-select').filter({has:page.locator(`#${id}`)}).locator('.ant-select-selector').click();
  await combo.fill(label);
  await page.locator('.ant-select-dropdown:not(.ant-select-dropdown-hidden) .ant-select-item-option-content').filter({hasText:label}).click();
 };
 await pick('teacherId','范围联验老师');await pick('courseId',originalCourse.name);
 const pickClass=async(value:string)=>{
  await draft.locator('.ant-select').filter({has:page.locator('#classType')}).locator('.ant-select-selector').click();
  await page.locator('.ant-select-dropdown:not(.ant-select-dropdown-hidden) .ant-select-item-option-content').filter({hasText:new RegExp(`^${value}$`)}).click();
 };
 await pickClass('1V2');
 await pick('studentIds','小明');await page.keyboard.press('Escape');
 const studentsResponse=await request.get(`${process.env.STARLINE_REAL_API}/api/students`,{headers});
 const secondStudent=(await studentsResponse.json()).data.find((item:{id:string})=>item.id==='stu-002');
 expect(secondStudent).toBeTruthy();
 await pick('studentIds',secondStudent.name);await page.keyboard.press('Escape');
 const future=new Date();future.setDate(future.getDate()+30);
 const plannedDate=[future.getFullYear(),String(future.getMonth()+1).padStart(2,'0'),String(future.getDate()).padStart(2,'0')].join('-');
 await draft.locator('#startDate').fill(plannedDate);await draft.locator('#startTime').fill('16:00');await draft.locator('#endTime').fill('17:00');
 await draft.locator('#expectedStudentCount').fill('');
 await pickClass('1V1');
 let prematureWrites=0;
 const countWrites=(response:import('@playwright/test').Response)=>{if(new URL(response.url()).pathname==='/api/schedule-classes'&&response.request().method()==='POST')prematureWrites++;};
 page.on('response',countWrites);
 await draft.getByRole('button',{name:'创建课程',exact:true}).click();
 await expect(draft.getByText('当前班型最多 1 名学生，请调整班型或学生',{exact:true})).toBeVisible();
 await expect(draft.locator('.ant-select').filter({has:page.locator('#studentIds')}).locator('.ant-select-selection-item')).toHaveCount(2);
 expect(prematureWrites).toBe(0);page.off('response',countWrites);
 await pickClass('1V2');
 await draft.getByRole('button',{name:'编辑老师授课范围',exact:true}).click();
 const scope=page.getByRole('dialog',{name:'编辑老师授课范围',exact:true});
 await scope.getByRole('button',{name:'添加授课范围',exact:true}).click();
 await select('授课年级','六年级',scope);await select('授课学科','English',scope);
 await scope.getByRole('button',{name:'保存范围',exact:true}).click();
 await expect(scope).not.toBeVisible();
 await expect(draft.locator('#startDate')).toHaveValue(plannedDate);await expect(draft.locator('#startTime')).toHaveValue('16:00');await expect(draft.locator('#endTime')).toHaveValue('17:00');
 await expect(draft.locator('.ant-select').filter({has:page.locator('#studentIds')})).toContainText('小明');
 await expect(draft.locator('.ant-select').filter({has:page.locator('#courseId')})).toContainText(originalCourse.name);
 await draft.locator('.ant-select').filter({has:page.locator('#courseId')}).locator('.ant-select-selector').click();
 await draft.locator('#courseId').fill('六年级范围联验课程');
 await expect(page.locator('.ant-select-dropdown:not(.ant-select-dropdown-hidden)').getByText('六年级范围联验课程',{exact:false})).toBeVisible();
 await page.keyboard.press('Escape');
 // Search never changes the selected original course.
 const savedResponse=page.waitForResponse(response=>new URL(response.url()).pathname==='/api/schedule-classes'&&response.request().method()==='POST');
 await draft.getByRole('button',{name:'创建课程',exact:true}).click();
 await page.getByRole('dialog',{name:'确认超出可上课时间',exact:true}).getByRole('button',{name:'已协调，继续排课',exact:true}).click();
 const created=await savedResponse;expect(created.ok()).toBeTruthy();
 const lesson=(await created.json()).data;
 expect(lesson.teacherId).toBe(teacher.id);expect(lesson.courseId).toBe(originalCourse.id);expect(lesson.startTime).toBe('16:00');expect(lesson.endTime).toBe('17:00');expect(lesson.lessonDate).toBe(plannedDate);expect(lesson.students.map((item:{id:string})=>item.id)).toEqual(['stu-001','stu-002']);expect(lesson.expectedStudentCount).toBe(2);
 await expect(draft).not.toBeVisible();
 const updatedResponse=await request.get(`${process.env.STARLINE_REAL_API}/api/teachers`,{headers});
 const expanded=(await updatedResponse.json()).data.find((item:{id:string})=>item.id===teacher.id);
 expect(expanded.learningSpaceIds).toContain('space-g06-english-s1-q1');expect(expanded.teacherLibrary.canDownload).toBe(false);expect(expanded.teacherLibrary.canManageCourses).toBe(false);expect(expanded.canUploadHandout).toBe(false);expect(expanded.canUploadQuestion).toBe(false);expect(expanded.canReview).toBe(false);
});
