package store

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"strings"

	"starline/learning-api/internal/domain/learning"
)

func directorySyncID(sourceID, nodeID, targetID string) string {
	sum := sha256.Sum256([]byte(sourceID + "\x00" + nodeID + "\x00" + targetID))
	return "dirsync-" + hex.EncodeToString(sum[:16])
}

// Full hierarchy identifies an existing branch; equal leaf names alone do not.
// IDs generated by a previous sync preserve identity on later rename/reorder.
func directoryPaths(nodes []learning.CurriculumNode) (map[string]string, error) {
	byID := map[string]learning.CurriculumNode{}
	for _, node := range nodes {
		byID[node.ID] = node
	}
	out := map[string]string{}
	seenPaths := map[string]bool{}
	for _, node := range nodes {
		parts := []string{}
		seen := map[string]bool{}
		for current := node; ; {
			if seen[current.ID] {
				return nil, errors.New("目录层级循环，不能同步")
			}
			seen[current.ID] = true
			part, _ := json.Marshal([]string{string(current.Type), curriculumNodePathLabel(current)})
			parts = append([]string{string(part)}, parts...)
			if current.ParentID == "" {
				break
			}
			parent, ok := byID[current.ParentID]
			if !ok {
				return nil, errors.New("目录缺少上级，不能同步")
			}
			current = parent
		}
		path := strings.Join(parts, "/")
		if seenPaths[path] {
			return nil, errors.New("目录存在相同完整路径，请先区分章节再同步")
		}
		seenPaths[path] = true
		out[node.ID] = path
	}
	return out, nil
}

func directoryLabels(nodes []learning.CurriculumNode) map[string]string {
	byID := map[string]learning.CurriculumNode{}
	for _, node := range nodes {
		byID[node.ID] = node
	}
	labels := map[string]string{}
	for _, node := range nodes {
		parts := []string{}
		for current := node; ; {
			parts = append([]string{curriculumNodePathLabel(current)}, parts...)
			if current.ParentID == "" {
				break
			}
			current = byID[current.ParentID]
		}
		labels[node.ID] = strings.Join(parts, " / ")
	}
	return labels
}

func (s *MemoryStore) directorySyncTarget(p learning.Principal, source learning.Course, targetID string) (learning.CourseDirectorySyncTarget, learning.Course) {
	out := learning.CourseDirectorySyncTarget{CourseID: targetID, Added: []string{}, Updated: []string{}}
	target, ok := s.findCourse(targetID)
	if !ok {
		out.Error = "目标课程不存在"
		return out, target
	}
	out.CourseName = target.Name
	if target.ID == source.ID || !p.CanMaintainCourses() || !canSeeCourse(p, target) || p.IsTeacherOnly() && !containsString(p.LearningSpaceIDs, target.LearningSpaceID) {
		out.Error = "没有权限同步该目标课程"
		return out, target
	}
	if !s.sameMaterialSyncScope(source, target) {
		out.Error = "目标课程必须与源课程的年级、学科、学期和阶段一致"
		return out, target
	}
	if target.Status != learning.StatusEnabled {
		out.Error = "目标课程已停用"
		return out, target
	}
	if source.FamilyID != "" && target.FamilyID == source.FamilyID {
		out.Status = "已共用目录"
		out.Preserved = len(target.Curriculum)
		return out, target
	}
	if target.FamilyID != "" {
		out.Error = "目标使用另一套共享目录，请在课程系列中维护"
		return out, target
	}
	sourcePaths, err := directoryPaths(source.Curriculum)
	if err != nil {
		out.Error = err.Error()
		return out, target
	}
	targetPaths, err := directoryPaths(target.Curriculum)
	if err != nil {
		out.Error = err.Error()
		return out, target
	}
	sourceLabels, targetLabels := directoryLabels(source.Curriculum), directoryLabels(target.Curriculum)
	byPath, byID := map[string]string{}, map[string]int{}
	merged := append([]learning.CurriculumNode(nil), target.Curriculum...)
	nextLinks := cloneMap(target.DirectorySyncMap)
	if nextLinks == nil {
		nextLinks = map[string]string{}
	}
	for i, node := range merged {
		byPath[targetPaths[node.ID]] = node.ID
		byID[node.ID] = i
	}
	mapping := map[string]string{}
	reserved := map[string]string{}
	for _, node := range source.Curriculum {
		linked := target.DirectorySyncMap[source.ID+":"+node.ID]
		if _, exists := byID[linked]; !exists {
			linked = directorySyncID(source.ID, node.ID, target.ID)
		}
		if _, exists := byID[linked]; exists {
			if owner := reserved[linked]; owner != "" && owner != node.ID {
				out.Error = "章节对应关系冲突，请先调整目录"
				return out, target
			}
			reserved[linked] = node.ID
		}
	}
	for _, node := range source.Curriculum {
		generated := directorySyncID(source.ID, node.ID, target.ID)
		linked := target.DirectorySyncMap[source.ID+":"+node.ID]
		if _, exists := byID[linked]; exists {
			mapping[node.ID] = linked
		} else if _, exists := byID[generated]; exists {
			mapping[node.ID] = generated
		} else if id := byPath[sourcePaths[node.ID]]; id != "" && (reserved[id] == "" || reserved[id] == node.ID) {
			mapping[node.ID] = id
		} else {
			mapping[node.ID] = generated
		}
		reserved[mapping[node.ID]] = node.ID
		nextLinks[source.ID+":"+node.ID] = mapping[node.ID]
	}
	matched := map[string]bool{}
	for _, node := range source.Curriculum {
		copy := node
		copy.ID = mapping[node.ID]
		copy.ParentID = mapping[node.ParentID]
		if index, exists := byID[copy.ID]; exists {
			matched[copy.ID] = true
			if merged[index] != copy {
				change := targetLabels[copy.ID] + " → " + sourceLabels[node.ID]
				if merged[index].ParentID != copy.ParentID {
					change += "（上级调整）"
				}
				out.Updated = append(out.Updated, change)
				merged[index] = copy
			}
		} else {
			out.Added = append(out.Added, sourceLabels[node.ID])
			merged = append(merged, copy)
		}
	}
	out.Preserved = len(target.Curriculum) - len(matched)
	target.Curriculum = merged
	target.DirectorySyncMap = nextLinks
	if err := s.validateCourseContentBindings(target); err != nil {
		out.Error = err.Error()
		return out, target
	}
	target.LessonCount = countCurriculumLessons(merged)
	// Source/target contents and scope are checked again immediately before write.
	original := s.courses[findCourseIndex(s.courses, targetID)]
	raw, _ := json.Marshal([]any{source, original, original.DirectorySyncMap})
	sum := sha256.Sum256(raw)
	out.Snapshot = hex.EncodeToString(sum[:])
	return out, target
}

func findCourseIndex(courses []learning.Course, id string) int {
	for i, course := range courses {
		if course.ID == id {
			return i
		}
	}
	return -1
}

func (s *MemoryStore) remapDirectorySyncLinks(courseID string, mapping map[string]string) {
	for i, course := range s.courses {
		if len(course.DirectorySyncMap) == 0 {
			continue
		}
		links := map[string]string{}
		for key, value := range course.DirectorySyncMap {
			if strings.HasPrefix(key, courseID+":") {
				if next := mapping[strings.TrimPrefix(key, courseID+":")]; next != "" {
					key = courseID + ":" + next
				}
			}
			if course.ID == courseID {
				if next := mapping[value]; next != "" {
					value = next
				}
			}
			links[key] = value
		}
		s.courses[i].DirectorySyncMap = links
	}
}

func (s *MemoryStore) directorySyncSource(p learning.Principal, req learning.CourseDirectorySyncRequest) (learning.Course, error) {
	source, ok := s.findCourse(strings.TrimSpace(req.SourceCourseID))
	if !p.CanMaintainCourses() || !ok || !canSeeCourse(p, source) {
		return source, errors.New("源课程不存在或无权访问")
	}
	if len(source.Curriculum) == 0 {
		return source, errors.New("源课程尚无目录")
	}
	if source.Status != learning.StatusEnabled {
		return source, errors.New("源课程已停用，请先启用课程")
	}
	if len(req.TargetCourseIDs) > 100 {
		return source, errors.New("单次最多同步 100 门课程")
	}
	if len(req.TargetCourseIDs) == 0 {
		return source, errors.New("请选择目标课程")
	}
	return source, nil
}

func (s *MemoryStore) PreviewCourseDirectorySync(p learning.Principal, req learning.CourseDirectorySyncRequest) (learning.CourseDirectorySyncResult, error) {
	s.mu.Lock()
	defer s.mu.Unlock()
	source, err := s.directorySyncSource(p, req)
	if err != nil {
		return learning.CourseDirectorySyncResult{}, err
	}
	out := learning.CourseDirectorySyncResult{Targets: []learning.CourseDirectorySyncTarget{}}
	seen := map[string]bool{}
	for _, rawID := range req.TargetCourseIDs {
		id := strings.TrimSpace(rawID)
		if seen[id] {
			continue
		}
		seen[id] = true
		preview, _ := s.directorySyncTarget(p, source, id)
		out.Targets = append(out.Targets, preview)
	}
	return out, nil
}

func (s *MemoryStore) SyncCourseDirectory(operator string, p learning.Principal, req learning.CourseDirectorySyncRequest) (learning.CourseDirectorySyncResult, error) {
	s.mu.Lock()
	defer s.mu.Unlock()
	return persistentMutation(s, func(work *MemoryStore) (learning.CourseDirectorySyncResult, error) {
		source, err := work.directorySyncSource(p, req)
		if err != nil {
			return learning.CourseDirectorySyncResult{}, err
		}
		out := learning.CourseDirectorySyncResult{Targets: []learning.CourseDirectorySyncTarget{}}
		seen := map[string]bool{}
		for _, rawID := range req.TargetCourseIDs {
			id := strings.TrimSpace(rawID)
			if seen[id] {
				continue
			}
			seen[id] = true
			preview, target := work.directorySyncTarget(p, source, id)
			if preview.Error == "" && preview.Status == "" {
				beforeLinks, _ := json.Marshal(work.courses[findCourseIndex(work.courses, id)].DirectorySyncMap)
				afterLinks, _ := json.Marshal(target.DirectorySyncMap)
				if len(preview.Added) == 0 && len(preview.Updated) == 0 && string(beforeLinks) == string(afterLinks) && req.Snapshots[id] != "" {
					preview.Status = "已同步"
				} else if req.Snapshots[id] == "" || req.Snapshots[id] != preview.Snapshot {
					preview.Error = "目录已发生变化，请重新预览"
				} else {
					work.courses[findCourseIndex(work.courses, id)] = target
					work.syncCourseReferences(target)
					work.prependLog(operator, "同步课程目录", source.Name+" → "+target.Name)
					preview.Status = "已同步"
				}
			}
			if preview.Error != "" {
				preview.Status = "失败"
			}
			out.Targets = append(out.Targets, preview)
		}
		return out, nil
	})
}
