package store

func contentRows(s *MemoryStore) []persistenceRow {
	rows := make([]persistenceRow, 0, len(s.courses)+len(s.materials)+len(s.homework)+len(s.questionBank)+len(s.fileAssets)+len(s.reviews)+len(s.submissions)+len(s.scoreRecords))
	for _, item := range s.courses {
		rows = append(rows, simpleRow("courses", "id", item.ID, `INSERT INTO courses (id, learning_space_id, name, subject, grade, status, chapter_count) VALUES (?, ?, ?, ?, ?, ?, ?) ON DUPLICATE KEY UPDATE learning_space_id=VALUES(learning_space_id), name=VALUES(name), subject=VALUES(subject), grade=VALUES(grade), status=VALUES(status), chapter_count=VALUES(chapter_count)`, item.ID, item.LearningSpaceID, item.Name, item.Subject, item.Grade, item.Status, item.ChapterCount))
	}
	for _, item := range s.materials {
		rows = append(rows, simpleRow("materials", "id", item.ID, `INSERT INTO materials (id, learning_space_id, course_id, title, chapter_name, material_type, owner_teacher_id, owner_teacher_name, publish_status, status, view_count, file_id, file_name, file_size, file_type, preview_status, preview_url, download_url) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) ON DUPLICATE KEY UPDATE learning_space_id=VALUES(learning_space_id), course_id=VALUES(course_id), title=VALUES(title), chapter_name=VALUES(chapter_name), material_type=VALUES(material_type), owner_teacher_id=VALUES(owner_teacher_id), owner_teacher_name=VALUES(owner_teacher_name), publish_status=VALUES(publish_status), status=VALUES(status), view_count=VALUES(view_count), file_id=VALUES(file_id), file_name=VALUES(file_name), file_size=VALUES(file_size), file_type=VALUES(file_type), preview_status=VALUES(preview_status), preview_url=VALUES(preview_url), download_url=VALUES(download_url)`, item.ID, item.LearningSpaceID, item.CourseID, item.Title, item.Chapter, item.Type, item.OwnerTeacherID, item.OwnerTeacherName, item.PublishStatus, item.Status, item.ViewCount, item.FileID, item.FileName, item.FileSize, item.FileType, item.PreviewStatus, item.PreviewURL, item.DownloadURL))
	}
	for _, item := range s.homework {
		rows = append(rows, simpleRow("homework_tasks", "id", item.ID, `INSERT INTO homework_tasks (id, learning_space_id, course_id, title, grade, semester, subject, question_ids_json, deadline, owner_teacher_id, owner_teacher_name, publish_status, status, package_name, question_num, submitted_num, total_num, file_id, file_name, file_size, file_type, preview_status, preview_url, download_url) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) ON DUPLICATE KEY UPDATE learning_space_id=VALUES(learning_space_id), course_id=VALUES(course_id), title=VALUES(title), grade=VALUES(grade), semester=VALUES(semester), subject=VALUES(subject), question_ids_json=VALUES(question_ids_json), deadline=VALUES(deadline), owner_teacher_id=VALUES(owner_teacher_id), owner_teacher_name=VALUES(owner_teacher_name), publish_status=VALUES(publish_status), status=VALUES(status), package_name=VALUES(package_name), question_num=VALUES(question_num), submitted_num=VALUES(submitted_num), total_num=VALUES(total_num), file_id=VALUES(file_id), file_name=VALUES(file_name), file_size=VALUES(file_size), file_type=VALUES(file_type), preview_status=VALUES(preview_status), preview_url=VALUES(preview_url), download_url=VALUES(download_url)`, item.ID, item.LearningSpaceID, item.CourseID, item.Title, item.Grade, item.Semester, item.Subject, mustJSON(item.QuestionIDs), nullableDate(item.Deadline), item.OwnerTeacherID, item.OwnerTeacherName, item.PublishStatus, item.Status, item.PackageName, item.QuestionNum, item.SubmittedNum, item.TotalNum, item.FileID, item.FileName, item.FileSize, item.FileType, item.PreviewStatus, item.PreviewURL, item.DownloadURL))
	}
	for _, item := range s.questionBank {
		rows = append(rows, simpleRow("question_bank_items", "id", item.ID, `INSERT INTO question_bank_items (id, title, grade, semester, subject, question_type, stem, options_json, answer, answers_json, score, status, owner_teacher_id, owner_teacher_name, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) ON DUPLICATE KEY UPDATE title=VALUES(title), grade=VALUES(grade), semester=VALUES(semester), subject=VALUES(subject), question_type=VALUES(question_type), stem=VALUES(stem), options_json=VALUES(options_json), answer=VALUES(answer), answers_json=VALUES(answers_json), score=VALUES(score), status=VALUES(status), owner_teacher_id=VALUES(owner_teacher_id), owner_teacher_name=VALUES(owner_teacher_name), updated_at=VALUES(updated_at)`, item.ID, item.Title, item.Grade, item.Semester, item.Subject, item.Type, item.Stem, mustJSON(item.Options), item.Answer, mustJSON(item.Answers), item.Score, item.Status, item.OwnerTeacherID, item.OwnerTeacherName, nullableDateTime(item.CreatedAt), nullableDateTime(item.UpdatedAt)))
	}
	for _, item := range s.fileAssets {
		rows = append(rows, simpleRow("starline_file_assets", "id", item.ID, `INSERT INTO starline_file_assets (id, file_name, file_size, file_type, content_type, original_path, preview_path, preview_status) VALUES (?, ?, ?, ?, ?, ?, ?, ?) ON DUPLICATE KEY UPDATE file_name=VALUES(file_name), file_size=VALUES(file_size), file_type=VALUES(file_type), content_type=VALUES(content_type), original_path=VALUES(original_path), preview_path=VALUES(preview_path), preview_status=VALUES(preview_status)`, item.ID, item.FileName, item.FileSize, item.FileType, item.ContentType, item.OriginalPath, item.PreviewPath, item.PreviewStatus))
	}
	for _, item := range s.reviews {
		rows = append(rows, simpleRow("pending_reviews", "id", item.ID, `INSERT INTO pending_reviews (id, student_id, homework_id, submission_id, student_name, package_name, homework_title, system_score, teacher_comment, reward, status) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) ON DUPLICATE KEY UPDATE student_id=VALUES(student_id), homework_id=VALUES(homework_id), submission_id=VALUES(submission_id), student_name=VALUES(student_name), package_name=VALUES(package_name), homework_title=VALUES(homework_title), system_score=VALUES(system_score), teacher_comment=VALUES(teacher_comment), reward=VALUES(reward), status=VALUES(status)`, item.ID, item.StudentID, item.HomeworkID, item.SubmissionID, item.StudentName, item.PackageName, item.Homework, item.SystemScore, item.TeacherComment, item.Reward, item.Status))
	}
	for _, item := range s.submissions {
		rows = append(rows, simpleRow("student_submission_results", "id", item.ID, `INSERT INTO student_submission_results (id, homework_id, student_id, task_title, score, objective_score, final_score, teacher_comment, reward, status, answers_json, created_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) ON DUPLICATE KEY UPDATE homework_id=VALUES(homework_id), student_id=VALUES(student_id), task_title=VALUES(task_title), score=VALUES(score), objective_score=VALUES(objective_score), final_score=VALUES(final_score), teacher_comment=VALUES(teacher_comment), reward=VALUES(reward), status=VALUES(status), answers_json=VALUES(answers_json)`, item.ID, item.HomeworkID, item.StudentID, item.TaskTitle, item.Score, item.ObjectiveScore, item.FinalScore, item.TeacherComment, item.Reward, item.Status, mustJSON(item.Answers), nullableDateTime(item.CreatedAt)))
	}
	for _, item := range s.scoreRecords {
		rows = append(rows, simpleRow("student_score_records", "id", item.ID, `INSERT INTO student_score_records (id, student_id, subject, exam_type, exam_name, exam_date, score, full_score, average_score, teacher_comment, created_by, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) ON DUPLICATE KEY UPDATE student_id=VALUES(student_id), subject=VALUES(subject), exam_type=VALUES(exam_type), exam_name=VALUES(exam_name), exam_date=VALUES(exam_date), score=VALUES(score), full_score=VALUES(full_score), average_score=VALUES(average_score), teacher_comment=VALUES(teacher_comment), created_by=VALUES(created_by), updated_at=VALUES(updated_at)`, item.ID, item.StudentID, item.Subject, firstNonEmpty(item.ExamType, "阶段测评"), item.ExamName, nullableDate(item.ExamDate), item.Score, item.FullScore, item.AverageScore, item.TeacherComment, item.CreatedBy, nullableDateTime(item.CreatedAt), nullableDateTime(item.UpdatedAt)))
	}
	return rows
}
