package store

func schedulingRows(s *MemoryStore) []persistenceRow {
	rows := make([]persistenceRow, 0, len(s.availability)+len(s.scheduleClasses)*2+len(s.lessonFeedbacks))
	for _, item := range s.availability {
		rows = append(rows, simpleRow("availability_slots", "id", item.ID, `INSERT INTO availability_slots (id, owner_type, owner_id, owner_name, day_of_week, start_time, end_time, start_date, end_date, remark) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?) ON DUPLICATE KEY UPDATE owner_type=VALUES(owner_type), owner_id=VALUES(owner_id), owner_name=VALUES(owner_name), day_of_week=VALUES(day_of_week), start_time=VALUES(start_time), end_time=VALUES(end_time), start_date=VALUES(start_date), end_date=VALUES(end_date), remark=VALUES(remark)`, item.ID, item.OwnerType, item.OwnerID, item.OwnerName, item.DayOfWeek, item.StartTime, item.EndTime, nullableDate(item.StartDate), nullableDate(item.EndDate), item.Remark))
	}
	for _, item := range s.scheduleClasses {
		rows = append(rows, simpleRow("schedule_classes", "id", item.ID, `INSERT INTO schedule_classes (id, name, course_id, course_name, teacher_id, teacher_name, campus_id, room_name, class_type, capacity, duration_minutes, day_of_week, start_time, end_time, start_date, end_date, expected_student_count, reservation_note, academic_year, semester, status, created_at, series_id, lesson_date, detached, override_note, audit_status, audit_reason, audited_by, audited_at, created_by, created_by_role) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) ON DUPLICATE KEY UPDATE name=VALUES(name), course_id=VALUES(course_id), course_name=VALUES(course_name), teacher_id=VALUES(teacher_id), teacher_name=VALUES(teacher_name), campus_id=VALUES(campus_id), room_name=VALUES(room_name), class_type=VALUES(class_type), capacity=VALUES(capacity), duration_minutes=VALUES(duration_minutes), day_of_week=VALUES(day_of_week), start_time=VALUES(start_time), end_time=VALUES(end_time), start_date=VALUES(start_date), end_date=VALUES(end_date), expected_student_count=VALUES(expected_student_count), reservation_note=VALUES(reservation_note), academic_year=VALUES(academic_year), semester=VALUES(semester), status=VALUES(status), series_id=VALUES(series_id), lesson_date=VALUES(lesson_date), detached=VALUES(detached), override_note=VALUES(override_note), audit_status=VALUES(audit_status), audit_reason=VALUES(audit_reason), audited_by=VALUES(audited_by), audited_at=VALUES(audited_at), created_by=VALUES(created_by), created_by_role=VALUES(created_by_role)`, item.ID, item.Name, item.CourseID, item.CourseName, item.TeacherID, item.TeacherName, item.CampusID, item.RoomName, item.ClassType, item.Capacity, item.DurationMinutes, item.DayOfWeek, item.StartTime, item.EndTime, nullableDate(item.StartDate), nullableDate(item.EndDate), item.ExpectedStudentCount, item.ReservationNote, item.AcademicYear, item.Semester, item.Status, nullableDateTime(item.CreatedAt), item.SeriesID, nullableDate(item.LessonDate), item.Detached, item.OverrideNote, item.AuditStatus, item.AuditReason, item.AuditedBy, nullableDateTime(item.AuditedAt), item.CreatedBy, item.CreatedByRole))
		for _, student := range item.Students {
			rows = append(rows, relationRow("schedule_class_students", []string{"schedule_class_id", "student_id"}, []any{item.ID, student.ID}, `INSERT INTO schedule_class_students (schedule_class_id, student_id, student_name) VALUES (?, ?, ?) ON DUPLICATE KEY UPDATE student_name=VALUES(student_name)`, item.ID, student.ID, student.Name))
		}
	}
	for _, item := range s.lessonFeedbacks {
		rows = append(rows, simpleRow("lesson_feedbacks", "id", item.ID, `INSERT INTO lesson_feedbacks (id, schedule_class_id, student_id, student_name, teacher_id, teacher_name, course_name, lesson_date, summary, homework, next_step, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) ON DUPLICATE KEY UPDATE summary=VALUES(summary), homework=VALUES(homework), next_step=VALUES(next_step), updated_at=VALUES(updated_at)`, item.ID, item.ScheduleClassID, item.StudentID, item.StudentName, item.TeacherID, item.TeacherName, item.CourseName, nullableDate(item.LessonDate), item.Summary, item.Homework, item.NextStep, nullableDateTime(item.CreatedAt), nullableDateTime(item.UpdatedAt)))
	}
	return rows
}
