package store

func contentRows(s *MemoryStore) []persistenceRow {
	rows := make([]persistenceRow, 0, len(s.courses)+len(s.materials)+len(s.homework)+len(s.questionBank)+len(s.fileAssets)+len(s.previewJobs)+len(s.reviews)+len(s.submissions)+len(s.scoreRecords))
	for _, item := range s.courses {
		rows = append(rows, simpleRow("courses", "id", item.ID, `INSERT INTO courses (id, learning_space_id, name, subject, grade, status, chapter_count, chapters_json) VALUES (?, ?, ?, ?, ?, ?, ?, ?) ON DUPLICATE KEY UPDATE learning_space_id=VALUES(learning_space_id), name=VALUES(name), subject=VALUES(subject), grade=VALUES(grade), status=VALUES(status), chapter_count=VALUES(chapter_count), chapters_json=VALUES(chapters_json)`, item.ID, item.LearningSpaceID, item.Name, item.Subject, item.Grade, item.Status, item.ChapterCount, mustJSON(item.Chapters)))
		for _, node := range item.Curriculum {
			rows = append(rows, simpleRow("course_curriculum_nodes", "id", node.ID, `INSERT INTO course_curriculum_nodes (id, course_id, parent_id, node_type, name, sort_order) VALUES (?, ?, ?, ?, ?, ?) ON DUPLICATE KEY UPDATE course_id=VALUES(course_id), parent_id=VALUES(parent_id), node_type=VALUES(node_type), name=VALUES(name), sort_order=VALUES(sort_order)`, node.ID, item.ID, node.ParentID, node.Type, node.Name, node.SortOrder))
		}
	}
	for _, item := range s.materials {
		rows = append(rows, simpleRow("materials", "id", item.ID, `INSERT INTO materials (id, learning_space_id, course_id, lesson_id, title, chapter_name, tag_code, material_type, owner_teacher_id, owner_teacher_name, publish_status, status, view_count, file_id, file_name, file_size, file_type, preview_status, preview_url, download_url, sort_order, created_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) ON DUPLICATE KEY UPDATE learning_space_id=VALUES(learning_space_id), course_id=VALUES(course_id), lesson_id=VALUES(lesson_id), title=VALUES(title), chapter_name=VALUES(chapter_name), tag_code=VALUES(tag_code), material_type=VALUES(material_type), owner_teacher_id=VALUES(owner_teacher_id), owner_teacher_name=VALUES(owner_teacher_name), publish_status=VALUES(publish_status), status=VALUES(status), view_count=VALUES(view_count), file_id=VALUES(file_id), file_name=VALUES(file_name), file_size=VALUES(file_size), file_type=VALUES(file_type), preview_status=VALUES(preview_status), preview_url=VALUES(preview_url), download_url=VALUES(download_url), sort_order=VALUES(sort_order)`, item.ID, item.LearningSpaceID, item.CourseID, item.LessonID, item.Title, item.Chapter, item.TagCode, item.Type, item.OwnerTeacherID, item.OwnerTeacherName, item.PublishStatus, item.Status, item.ViewCount, item.FileID, item.FileName, item.FileSize, item.FileType, item.PreviewStatus, item.PreviewURL, item.DownloadURL, item.SortOrder, nullableDateTime(item.CreatedAt)))
	}
	for _, item := range s.homework {
		rows = append(rows, simpleRow("homework_tasks", "id", item.ID, `INSERT INTO homework_tasks (id, learning_space_id, course_id, lesson_id, title, chapter_name, tag_code, grade, semester, subject, question_ids_json, deadline, deadline_at, assessment_type, owner_teacher_id, owner_teacher_name, publish_status, status, sort_order, package_name, question_num, submitted_num, total_num, file_id, file_name, file_size, file_type, preview_status, preview_url, download_url) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) ON DUPLICATE KEY UPDATE learning_space_id=VALUES(learning_space_id), course_id=VALUES(course_id), lesson_id=VALUES(lesson_id), title=VALUES(title), chapter_name=VALUES(chapter_name), tag_code=VALUES(tag_code), grade=VALUES(grade), semester=VALUES(semester), subject=VALUES(subject), question_ids_json=VALUES(question_ids_json), deadline=VALUES(deadline), deadline_at=VALUES(deadline_at), assessment_type=VALUES(assessment_type), owner_teacher_id=VALUES(owner_teacher_id), owner_teacher_name=VALUES(owner_teacher_name), publish_status=VALUES(publish_status), status=VALUES(status), sort_order=VALUES(sort_order), package_name=VALUES(package_name), question_num=VALUES(question_num), submitted_num=VALUES(submitted_num), total_num=VALUES(total_num), file_id=VALUES(file_id), file_name=VALUES(file_name), file_size=VALUES(file_size), file_type=VALUES(file_type), preview_status=VALUES(preview_status), preview_url=VALUES(preview_url), download_url=VALUES(download_url)`, item.ID, item.LearningSpaceID, item.CourseID, item.LessonID, item.Title, item.Chapter, item.TagCode, item.Grade, item.Semester, item.Subject, mustJSON(item.QuestionIDs), nullableDate(item.Deadline), nullableDateTime(item.DeadlineAt), item.AssessmentType, item.OwnerTeacherID, item.OwnerTeacherName, item.PublishStatus, item.Status, item.SortOrder, item.PackageName, item.QuestionNum, item.SubmittedNum, item.TotalNum, item.FileID, item.FileName, item.FileSize, item.FileType, item.PreviewStatus, item.PreviewURL, item.DownloadURL))
	}
	for _, item := range s.questionBank {
		rows = append(rows, simpleRow("question_bank_items", "id", item.ID, `INSERT INTO question_bank_items (id, title, grade, semester, subject, question_type, stem, options_json, answer, answers_json, score, status, owner_teacher_id, owner_teacher_name, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) ON DUPLICATE KEY UPDATE title=VALUES(title), grade=VALUES(grade), semester=VALUES(semester), subject=VALUES(subject), question_type=VALUES(question_type), stem=VALUES(stem), options_json=VALUES(options_json), answer=VALUES(answer), answers_json=VALUES(answers_json), score=VALUES(score), status=VALUES(status), owner_teacher_id=VALUES(owner_teacher_id), owner_teacher_name=VALUES(owner_teacher_name), updated_at=VALUES(updated_at)`, item.ID, item.Title, item.Grade, item.Semester, item.Subject, item.Type, item.Stem, mustJSON(item.Options), item.Answer, mustJSON(item.Answers), item.Score, item.Status, item.OwnerTeacherID, item.OwnerTeacherName, nullableDateTime(item.CreatedAt), nullableDateTime(item.UpdatedAt)))
	}
	for _, item := range s.fileAssets {
		rows = append(rows, simpleRow("starline_file_assets", "id", item.ID, `INSERT INTO starline_file_assets (id, file_name, file_size, file_type, content_type, original_path, preview_path, preview_page_dir, preview_page_count, preview_status, preview_error) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) ON DUPLICATE KEY UPDATE file_name=VALUES(file_name), file_size=VALUES(file_size), file_type=VALUES(file_type), content_type=VALUES(content_type), original_path=VALUES(original_path), preview_path=VALUES(preview_path), preview_page_dir=VALUES(preview_page_dir), preview_page_count=VALUES(preview_page_count), preview_status=VALUES(preview_status), preview_error=VALUES(preview_error)`, item.ID, item.FileName, item.FileSize, item.FileType, item.ContentType, item.OriginalPath, item.PreviewPath, item.PreviewPageDir, item.PreviewPageCount, item.PreviewStatus, item.PreviewError))
	}
	for _, item := range s.previewJobs {
		rows = append(rows, simpleRow("preview_jobs", "id", item.ID, `INSERT INTO preview_jobs (id, file_id, status, attempt_count, error_message, created_at, started_at, finished_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?) ON DUPLICATE KEY UPDATE file_id=VALUES(file_id), status=VALUES(status), attempt_count=VALUES(attempt_count), error_message=VALUES(error_message), started_at=VALUES(started_at), finished_at=VALUES(finished_at)`, item.ID, item.FileID, item.Status, item.AttemptCount, item.ErrorMessage, nullableDateTime(item.CreatedAt), nullableDateTime(item.StartedAt), nullableDateTime(item.FinishedAt)))
	}
	for _, item := range s.reviews {
		rows = append(rows, simpleRow("pending_reviews", "id", item.ID, `INSERT INTO pending_reviews (id, student_id, homework_id, submission_id, student_name, package_name, homework_title, system_score, teacher_comment, reward, status, reviewer_teacher_id, reviewer_teacher_name, tutoring_assignment_id, assigned_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) ON DUPLICATE KEY UPDATE student_id=VALUES(student_id), homework_id=VALUES(homework_id), submission_id=VALUES(submission_id), student_name=VALUES(student_name), package_name=VALUES(package_name), homework_title=VALUES(homework_title), system_score=VALUES(system_score), teacher_comment=VALUES(teacher_comment), reward=VALUES(reward), status=VALUES(status), reviewer_teacher_id=VALUES(reviewer_teacher_id), reviewer_teacher_name=VALUES(reviewer_teacher_name), tutoring_assignment_id=VALUES(tutoring_assignment_id), assigned_at=VALUES(assigned_at)`, item.ID, item.StudentID, item.HomeworkID, item.SubmissionID, item.StudentName, item.PackageName, item.Homework, item.SystemScore, item.TeacherComment, item.Reward, item.Status, item.ReviewerTeacherID, item.ReviewerTeacherName, item.TutoringAssignmentID, nullableDateTime(item.AssignedAt)))
	}
	for _, item := range s.submissions {
		rows = append(rows, simpleRow("student_submission_results", "id", item.ID, `INSERT INTO student_submission_results (id, homework_id, student_id, task_title, score, objective_score, final_score, teacher_comment, reward, status, answers_json, created_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) ON DUPLICATE KEY UPDATE homework_id=VALUES(homework_id), student_id=VALUES(student_id), task_title=VALUES(task_title), score=VALUES(score), objective_score=VALUES(objective_score), final_score=VALUES(final_score), teacher_comment=VALUES(teacher_comment), reward=VALUES(reward), status=VALUES(status), answers_json=VALUES(answers_json)`, item.ID, item.HomeworkID, item.StudentID, item.TaskTitle, item.Score, item.ObjectiveScore, item.FinalScore, item.TeacherComment, item.Reward, item.Status, mustJSON(item.Answers), nullableDateTime(item.CreatedAt)))
	}
	for _, item := range s.scoreRecords {
		rows = append(rows, simpleRow("student_score_records", "id", item.ID, `INSERT INTO student_score_records (id, student_id, subject, exam_type, exam_name, exam_date, score, full_score, average_score, teacher_comment, created_by, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) ON DUPLICATE KEY UPDATE student_id=VALUES(student_id), subject=VALUES(subject), exam_type=VALUES(exam_type), exam_name=VALUES(exam_name), exam_date=VALUES(exam_date), score=VALUES(score), full_score=VALUES(full_score), average_score=VALUES(average_score), teacher_comment=VALUES(teacher_comment), created_by=VALUES(created_by), updated_at=VALUES(updated_at)`, item.ID, item.StudentID, item.Subject, firstNonEmpty(item.ExamType, "阶段测评"), item.ExamName, nullableDate(item.ExamDate), item.Score, item.FullScore, item.AverageScore, item.TeacherComment, item.CreatedBy, nullableDateTime(item.CreatedAt), nullableDateTime(item.UpdatedAt)))
	}
	return rows
}
